### ISSUE TITLE
Rails form model support

### ISSUE THREAD

**Issue by fguillen** [yammer/model_attribute#15]
I suggest to make it clear in the README that if you want to use this Models in your Rails form you will need to add:

```
include ActiveModel::Conversion
extend  ActiveModel::Naming

def persisted?
  false
end
```

To your model

**Comment by dwaller** [comment]
It's a good tip, thanks for the suggestion and taking the time to help improve the gem!

I want to avoid being too prescriptive about how the gem is used.  At Yammer we don't use it in forms at all, so none of this code is necessary.  For our use `ActiveModel::Callbacks` is important, to integrate with other gems that expect that callback interface, and we use a small mixin we called `ActiveRecordMimic`, as [I described in a blog post](https://medium.com/yammer-engineering/activerecord-stole-my-data-and-now-i-want-it-back-3041ac4eb163) - [you can see the full source here](https://gist.github.com/dwaller/5474304cfea354a9701d).  

I think what I'll do is add something that suggests looking at these sort of integrations, rather than trying to cover specific use cases.  The [ActiveModel guide](https://guides.rubyonrails.org/active_model_basics.html) is generally very useful.

**Comment by dwaller** [comment]
I've made those changed in the linked PR - let me know what you think.
