### ISSUE TITLE
JSON type doesn't accept hashes with symbol keys

### ISSUE THREAD

**Issue by nickcampbell18** [yammer/model_attribute#6]
``` ruby
class Foo
  attribute :metadata, :json
end

instance = Foo.new
```

If you give a Hash with string keys, all is well:

``` ruby
instance.metadata = {"master" => "chief"}
#=> {"master" => "chief"}
```

However, if you provide a Hash with symbol keys (which might have happened depending on how your JSON was generated or if it came from elsewhere e.g. Yaml):

``` ruby
instance.metadata = {:master => "chief"}
#=> ArgumentError: JSON only supports nil, numeric, string, boolean and arrays and hashes of those.
```

I think this is a bug because it's non-obvious behaviour, especially in Ruby where hashes can have ambiguous key semantics. There's probably three solutions:
1. Sanitise your inputs! (Nested stringify all your keys before pushing into the model)
2. Stringify keys with the writer (`metadata=`) method
3. Accept symbol keys, potentially the primitive type "symbol" (even knowing that JSON doesn't recognise that type).

**Comment by nickcampbell18** [comment]
@dwaller any thoughts here?

**Comment by dwaller** [comment]
When I wrote the JSON support, I took the position that being inflexible, but unambiguous, was the best course.  Here's how that plays out with your suggestions:

1. Sanitise your inputs.  You understand exactly what's happening to your hash because it's happening in code you wrote.  Unambiguous, but inconvenient.
2. Stringify the keys with the writer.  You write a hash with symbol keys, but when you read it again it's got string keys, and so `my_attribute[:some_key]` surprisingly returns `nil`.
3. Accept symbol keys.  Now `my_attribute[:some_key]` works as you expect if you just assigned the hash, but not if you just loaded it from JSON (with real string keys).  Also strict JSON serialisation fails (e.g. using the Oj gem in strict mode to serialise the result of `#attributes_for_json`).

**Comment by nickcampbell18** [comment]
Yes, for 2) I now remember why I distrust `HashWithIndifferentAccess`.

**Comment by dwaller** [comment]
Given this, I still think it's best to stick with the current behaviour (1).  If a user of the library wants (2) then they can override the writer method to do this.  (3) I don't favour, as it makes the contents of the attribute unpredictable.

**Comment by dwaller** [comment]
Tidying up - I think this issue can be closed, and ModelAttribute sticks with its strict position on keys.
